markets:
  MARKET_A0:
    spawn_loc:
      world: w_market_0
      x: 1
      y: 1
      z: 1
      yaw: 1
      pitch: 1
    display_name: '淘物城'
    welcome_msg: '%head_msg%欢迎来到淘物城,在这里你能买到许多强大的装备~'
    enter_give_horse: true
