markets:
  MARKET_A0:
    spawn_loc:
      world: w_market_0
      x: 1
      y: 1
      z: 1
      yaw: 1
      pitch: 1
    displayName: '淘物城'
    welcomeMsg: '%head_msg%欢迎来到淘物城,在这里你能买到许多强大的装备~'
    enterGiveHorse: true
